### ISSUE TITLE
GUI control of focus servo needs improvement

### ISSUE THREAD

**Issue by BadenLab** [amchagas/Flypi#19]
The GUI currently controls servo movements with a single slider. The moment the slider is dragged, the servo starts moving and only stops when the slider is reset to zero. This system makes it very hard to accurately focus at high zoom. Instead, it would be helpful if some controls could be added that move the servo in small installments e.g. upon clicking a "execute" button or similar.

**Comment by amchagas** [comment]
Found an old piece of code from Ihab. re-implemented back in the GUI. 
Should work now.
