### ISSUE TITLE
Which Arduino file to write into the board

### ISSUE THREAD

**Issue by jtx1999** [amchagas/Flypi#24]
Hi,
I was just wondering which Arduino file should I write into the Arduino board, since there are several files in the Arduino folder.
Also, is there missing something on page 5 of the assembly manual? After installing the Adafruit libraries, further steps are not specified.
Thanks!

**Comment by amchagas** [comment]
Hi!
thanks for your feedback. The file you should use is the fly_pi_development.ino file. Overall I would also suggest getting all the files from the repo where we are continuing the development https://github.com/prometheus-science/Flypi
