### ISSUE TITLE
BOM: References have leaked into into quantity column

### ISSUE THREAD

**Issue by kasbah** [amchagas/Flypi#29]
E.g. https://github.com/amchagas/Flypi/blob/master/PCB/flypi_pcb_kicad/1-click-bom.csv#L4

Kitspace build is failing because of this.

**Comment by amchagas** [comment]
Thanks for the heads up. Will check in a bit!

**Comment by amchagas** [comment]
updated the csv file. 
There shouldn't be any more "leaks"
Although the last item is not present in any manufacturers, and I added the link to the place we buy it from. Is that ok?

**Comment by kasbah** [comment]
Yeah, that's fine. It's you BOM :smile:  I would put it in a separate links column but It won't break anything.
