### ISSUE TITLE
Microbiology Extension "MiPi" (Summary)

### ISSUE THREAD

**Issue by vektorious** [amchagas/Flypi#30]
**We want to create new FlyPi modules for microbiology applications!**

This issue collects all the possible MiPi modules and links the respective module issue. Please post any general ideas and comments right here.

Module ideas: 
- Agar plate imaging and colony counting module
- Colony size/migration area analysis tool
- Colony shape identification
- Blue/white screening help
usw.

**Comment by amchagas** [comment]
I think we can close this one, since as far as I know the MiPi project took a different direction
