### ISSUE TITLE
Boxes closing system breaks

### ISSUE THREAD

**Issue by amchagas** [amchagas/Flypi#42]
The system to keep the boxes closed is too fragile, as the stress points are in the same axis as the printed parts. it would be great to develop a new closing/clicking system for the boxes where the locking parts do not break so easily. 

Here are the files for the boxes:
Raspberry pi case
https://github.com/amchagas/Flypi/blob/master/3D_print_files/v2.0/STEPs/RaspberryCase_Top.stp

https://github.com/amchagas/Flypi/blob/master/3D_print_files/v2.0/STEPs/RaspberryCase_Rails.stp

https://github.com/amchagas/Flypi/blob/master/3D_print_files/v2.0/STEPs/RaspberryCase_Bot.stp

PCB case:

https://github.com/amchagas/Flypi/blob/master/3D_print_files/v2.0/STEPs/PCBCase_Top.stp

https://github.com/amchagas/Flypi/blob/master/3D_print_files/v2.0/STEPs/PCBCase_Bot.stp

**Comment by isobianin** [comment]
Hello. In the Raspberry case I have added stiffeners along the exterior of hull. The bottom part remains unchanged and so there is no need in reprinting. 
![raspberry_top](https://user-images.githubusercontent.com/52375129/61581698-2f2d8800-ab2a-11e9-80e1-4f5d8fc5ec5b.jpg)
Do you need an analogous improvement in PCB case as it is in these repository or the end result must only meet criterias defined in #43? 
[RaspberryCase_Top.zip](https://github.com/amchagas/Flypi/files/3413827/RaspberryCase_Top.zip)

**Comment by amchagas** [comment]
Hi!

thjanks for this, Il try to print it today and let you know how it went. In principle we also need something like this for the PCB case...

**Comment by amchagas** [comment]
hi, 
So this worked quite well! The snaps are much more resistant now, but still flexible enough that they click on the bottom part of the board!

**Comment by amchagas** [comment]
Solved by @isobianin contribution via PR https://github.com/amchagas/Flypi/commit/50d048502420fd8981893c8c185ba7404e968846
