### ISSUE TITLE
acessing cables without unmounting the boxes

### ISSUE THREAD

**Issue by amchagas** [amchagas/Flypi#43]
In order to plug and unplug modules, users need to disassemble at least the PCB box. 
What we want is to create a click on or flipping system where the modules can be plugged and unplugged in an easier manner. 

Here are the files for the PCB box, where the modules are plugged in and out:

https://github.com/amchagas/Flypi/blob/master/3D_print_files/v2.0/STEPs/PCBCase_Top.stp

https://github.com/amchagas/Flypi/blob/master/3D_print_files/v2.0/STEPs/PCBCase_Bot.stp

**Comment by isobianin** [comment]
Does the highlighted hole serve functional purpose? What exactly it does?
![question](https://user-images.githubusercontent.com/52375129/61583202-72452680-ab3d-11e9-843a-0e88042daacd.png)

**Comment by isobianin** [comment]
I have in mind a pair of hinges that will be placed either there or where the hooks currently are. I thought that this side of enclosure is less likely to be loaded with ports but I do not know the used PCB layout

**Comment by amchagas** [comment]
Hi, sorry it took me a moment to take a photo of the case with the cables and a part of the pcb.

![IMG_20190722_070913](https://user-images.githubusercontent.com/3624486/61654814-274e1f00-acb5-11e9-837c-c1eed09192bd.jpg)
![IMG_20190722_070838](https://user-images.githubusercontent.com/3624486/61654824-2b7a3c80-acb5-11e9-9d72-8cab267053b1.jpg)

**Comment by isobianin** [comment]
Thanks for the photo! It is quite informative! However, I still have questions. Is the opposite side of the box (pcb) loaded with cables or ports too? I don’t see it in this photos, but structure of the enclosure have holes for ports there.
It is important for the hinge system I want to implement

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by isobianin** [comment]
Yeah, I see that both sides are loaded

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by isobianin** [comment]
Hello @amchagas . I am almost finished with the new design. For now a test for hinges is needed 
[hinge_test.zip](https://github.com/amchagas/Flypi/files/3442756/hinge_test.zip)

**Comment by amchagas** [comment]
hi @isobianin, great, thanks! can print these tomorrow

**Comment by isobianin** [comment]
So this is what I came up with. The first picture demonstrates hinges placement
![PCB_case mod_1](https://user-images.githubusercontent.com/52375129/62069702-8d9ce980-b241-11e9-96ab-7db8224a75d4.png)
The second one illustrates clicking system from this same enclosure with stifeners (as in #42)
![PCB_case mod_2](https://user-images.githubusercontent.com/52375129/62069703-8d9ce980-b241-11e9-9aba-0572c0d7ed22.png)
In the third picture you can see how the case looks being open
![PCB_case mod_3](https://user-images.githubusercontent.com/52375129/62069705-8e358000-b241-11e9-9209-b408c839edc3.png)
Attaching step files in case printing phase goes well and hinges fit.
[PCB_mod.zip](https://github.com/amchagas/Flypi/files/3443610/PCB_mod.zip)

**Comment by amchagas** [comment]
Hey!
so I managed to print this, and there is one main issue, namely that the tabs in the bottom part are too thin and they broke right off in the first opening of the system... I wonder if making them thicker would be too much trouble?
![IMG_20190807_152431907](https://user-images.githubusercontent.com/3624486/62774965-4bc03e80-ba9e-11e9-8f6c-18204c052267.jpg)

**Comment by isobianin** [comment]
Hi. Okay, I will correct strength of the detail. Shame that this occurred on the printed parts

**Comment by isobianin** [comment]
Error (10.08.2019) in this message was patched (11.08.2019)

Increased thickness of wall towards hull (pic. 1)
![walls](https://user-images.githubusercontent.com/52375129/62820875-92339d00-bb73-11e9-8c1d-d0052c2f7bd0.jpg)
Pic. 1 Thickness
[PCBCase_Bot_mod_v2_checked.zip](https://github.com/amchagas/Flypi/files/3490241/PCBCase_Bot_mod_v2_checked.zip)

**Comment by isobianin** [comment]
Created another variant of hinges that are more stable, however, they take a bit more place in the interior (pic.1-pic.4)
![bot_alternate](https://user-images.githubusercontent.com/52375129/62837829-c47cf180-bc7c-11e9-9d11-ea0f5862128a.JPG)
Pic. 1 - Bottom
![top_alternate](https://user-images.githubusercontent.com/52375129/62837842-e5dddd80-bc7c-11e9-9daa-a52415cdad9d.JPG)
Pic. 2 - Top (outside view)
![top_alternate_inside](https://user-images.githubusercontent.com/52375129/62837849-ff7f2500-bc7c-11e9-9bad-bdd5d30dd915.JPG)
Pic. 3 - Top (inside view)
![box_assembly_check](https://user-images.githubusercontent.com/52375129/62837862-1e7db700-bc7d-11e9-8685-165b1b34bfaf.JPG)
Pic. 4 - Assembled
![box_assembly_check_open](https://user-images.githubusercontent.com/52375129/62837864-29d0e280-bc7d-11e9-93a8-b2b8c669cfc3.JPG)
Pic. 5 - Opened
[PCB_case_alternate.zip](https://github.com/amchagas/Flypi/files/3490288/PCB_case_alternate.zip)

**Comment by amchagas** [comment]
Hi! so here is the new version printed. 
It looks quite nice and the hinges do not break :) 

There is only a bit of rubbing on the one component when opening it.. but I think, if possible, making that printed part a bit slimmer should do the trick?

![IMG_20190815_094844197](https://user-images.githubusercontent.com/3624486/63084552-56b61b80-bf43-11e9-9c19-febd4673f3fe.jpg)
![IMG_20190815_094911599](https://user-images.githubusercontent.com/3624486/63084554-587fdf00-bf43-11e9-84c3-91dd749d8529.jpg)

**Comment by amchagas** [comment]
I think we are ready to call this one closed?

**Comment by isobianin** [comment]
Here is patched version (pic. 1)
![box_assembly_check_kurz](https://user-images.githubusercontent.com/52375129/63090171-20889400-bf63-11e9-9d22-6eb60fabe039.JPG)
Pic. 1 - Short version
Actually, having step file with pcb layout would have been nice, but are almost finished with this one
[pcb_case_short.zip](https://github.com/amchagas/Flypi/files/3505270/pcb_case_short.zip)

**Comment by isobianin** [comment]
Adjusted tolerances based on the latest (26.08.2019) prototype
[PCBCase_Bot_v2.zip](https://github.com/amchagas/Flypi/files/3550609/PCBCase_Bot_v2.zip)

**Comment by amchagas** [comment]
Solved by @isobianin contribution via PR https://github.com/amchagas/Flypi/commit/50d048502420fd8981893c8c185ba7404e968846
