### ISSUE TITLE
base optimizations

### ISSUE THREAD

**Issue by amchagas** [amchagas/Flypi#44]
The base could use some optimizations:

1 - Currently it takes quite a while to print, it would be useful to hollow out some parts so that it prints faster. It should be kept in mind that hollow parts require some sort of support/bridge to print properly.

2 - on the top side of the base, where the peltier cables go in, one of the sides is higher then the other. we want to fix that by making both sides as low as the current lowest side and to make the slits curved and not squared as they are currently (this will lead to better finishing when it is printed)

file for the base https://github.com/amchagas/Flypi/blob/master/3D_print_files/v2.0/STEPs/Base.stp

**Comment by amchagas** [comment]
https://github.com/amchagas/Flypi/blob/master/3D_print_files/v2.0/STEPs/Base.stp

**Comment by isobianin** [comment]
Want

**Comment by isobianin** [comment]
Here I have multiple questions:
1. Is this an orientation for the printing?
![orientation](https://user-images.githubusercontent.com/52375129/61589676-2da9a180-abb6-11e9-8688-86faa9b417fb.png)
2. What are the functional purpose of all holes and how does this part connects to the others? Some triangular holes are blocked (picture below). Need to know more because I want to create holes as shown in the picture.
![base_holes](https://user-images.githubusercontent.com/52375129/61589691-7eb99580-abb6-11e9-978e-201459d46bd3.png)
3. Have a problem with the second point of this issue. Do the circled points show the slits for peltier cables (picture below)? At least, I think so. In this case, there is now difference in height between slits (pink lines in the picture)
![Base slits](https://user-images.githubusercontent.com/52375129/61589623-55e4d080-abb5-11e9-9c47-f0c01fe2d3f7.png)

**Comment by amchagas** [comment]
hi @isobianin ,
to answer your questions:
1 yes, the base is printed upside down, as you show in 1.

2. the triangular holes are used as fits for the necks (https://github.com/amchagas/Flypi/blob/master/3D_print_files/v2.0/STLs/Neck_L.stl). The pieces "blocking" the necks are not actually blocking this fit, and they are there to hold a fan in place (placed from below to be sitting under the peltier element).

3 yes, this part of the issue was resolved already.. sorry for not updating the description.

**Comment by isobianin** [comment]
Hi @amchagas , thanks for information. But the slits are still need to be curved, right?

**Comment by amchagas** [comment]
You mean so that the cables fit in them? I think it is not that pressing, since squared slits are working fine too..

**Comment by isobianin** [comment]
Okay, leaving it squared

**Comment by isobianin** [comment]
Hi @amchagas . Here is an update on this issue. Picture one shows amount of material before.
![Base_before](https://user-images.githubusercontent.com/52375129/62194424-816c7580-b382-11e9-95c2-0c989d343a9c.png)
Pic. 1 - Slice of model (before)
The next one - after rework.
![Base_after](https://user-images.githubusercontent.com/52375129/62194441-89c4b080-b382-11e9-8824-c426573b65a0.png)
Pic. 2 - Slice of model (after)
![Base_light_2](https://user-images.githubusercontent.com/52375129/62194882-69492600-b383-11e9-9540-9b92151511f8.png)
Pic. 3 - Light version of the base
For example, numeracly it can be shown as following:
V = 62330.061064 mm3 (before)
V = 22574.223411 mm3 (after)
Almost 3 times lighter. 
Attaching file to this comment and waiting for your approval of this design
[Base_light.zip](https://github.com/amchagas/Flypi/files/3450480/Base_light.zip)

**Comment by amchagas** [comment]
Hi, 
So I managed to print this and indeed it cut the printing time in half!
There is one issue though that the most inner wall is too thin and breaks easily... would it be hard to increase the wall thickness a bit, or add reinforces along the wall? (as long as it doesn't cover the triangular holes?
![IMG_20190812_145047735](https://user-images.githubusercontent.com/3624486/63009268-0cb63280-be7c-11e9-85de-e604b81d109c.jpg)
)

**Comment by isobianin** [comment]
Okay, I will make necessary adjustments

**Comment by isobianin** [comment]
I have looked up my model. So is there a problem in all other walls too? Because they are all the same and have 1.5 mm thickness

**Comment by amchagas** [comment]
I think the problem is mostly with the inner ones... maybe the bridges and other elements closer to the outter walls somehow make them stiffer?
Or maybe there is an issue with the slicing software, but then this is something that is not easy to change from our side...

**Comment by isobianin** [comment]
Hey. Increased thickness of inner walls by 1 mm. (pic. 1, pic. 2)
![base_light_reinforced](https://user-images.githubusercontent.com/52375129/63173339-6408fe00-c048-11e9-94db-2f8d10df8d98.JPG)
Pic. 1 Reinforced model
![base_light_reinforced interior](https://user-images.githubusercontent.com/52375129/63173343-6703ee80-c048-11e9-8a57-06eb4c1583e1.JPG)
Pic. 2 Interior
[base_light_reinforced.zip](https://github.com/amchagas/Flypi/files/3509923/base_light_reinforced.zip)

**Comment by amchagas** [comment]
Solved by @isobianin contribution via PR https://github.com/amchagas/Flypi/commit/50d048502420fd8981893c8c185ba7404e968846
