### ISSUE TITLE
USB connectors and inductors footprint

### ISSUE THREAD

**Issue by ifriad** [amchagas/Flypi#8]
It will be very useful if the connectors to the ring, fan, etc. were changed to USB_A. This will make it easier for users to plug in/out external modules at their convention.

Please also take care of the inductors footprint on the PCB, they are of the wrong size.

**Comment by amchagas** [comment]
Hi Ihab,
we solved these and other issues on the Prometheus fork where development is continuing https://github.com/prometheus-science/Flypi

**Comment by amchagas** [comment]
@all-contributors please add @ifriad for design, code

**Comment by amchagas** [comment]
@all-contributors please add @ifriad for design, code

**Comment by amchagas** [comment]
@all-contributors please add @GrandeCappucino for design, code

**Comment by amchagas** [comment]
@all-contributors please add @TomBaden  for design, code

**Comment by amchagas** [comment]
@all-contributors please add @GrandeCappuccino for design

**Comment by amchagas** [comment]
@all-contributors please add @icaven  for design

**Comment by amchagas** [comment]
l-contributors please add @amchagas  for design, code, documentation

**Comment by amchagas** [comment]
@all-contributors please add @amchagas for design, code, documentation
